### ISSUE TITLE
Not able to access user login page

### ISSUE THREAD

**Issue by prashant1989** [GraseHotspot/grase-www-portal#173]
Hi Guys,

I have installed grase hotspot using installation wiki page. I installed it on ubuntu 14.4 LTS on virtualbox vm. My host os is Windows 8. Grase hotspot is correctly installed. I can able to access and login in below url:
http://10.1.0.1/grase/radmin/ page. 

But when I access http://10.1.0.1/grase/ it is redirected to http://10.1.0.1:3990/prelogin. This page shows message, Site cannot be reached. connection reset. User login page is not loading.

Note: I am accessing above mentioned url from host. I correctly forwarded port 80 and 3990 from guest to host.  I also assigned static ip 10.1.0.1  to my oracle virtualbox. I created this box using vagrant.

I am not able to debug this, because i am not getting any error. And also don't know how to debug this issue. Because I can able to access admin pages.

Please let me know, I am doing something wrong. Please guide me in right direction.

Thanks
-PB

**Comment by timwhite** [comment]
You should really be asking this on the mailing list (https://grasehotspot.org/support/mailing-list/) as the Github issues are for bugs.

Your problem is that the login pages can only be accessed from clients due to how Coova Chilli works. If running in a VM, the "LAN" interface needs to be L2 bridged to your clients network. Once a client on that network has gotten an IP via DHCP, then it will be able to login. You should not set 10.1.0.1 as a static IP on the virtualbox, it should be set within the Grase Hotspot
